apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rayservice-cpu.yaml
configMapGenerator:
  - name: video-intelligence-app
    files:
      - ../serve_app.py
generatorOptions:
  disableNameSuffixHash: true
